import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import {  NextUiClientProvider } from './components/nextui-provider'
import { getServerSession }  from "next-auth"
import SessionProvider from './components/session-provider';
import NavbarComponent from './components/nav-bar/nav-bar';

const inter = Inter({ subsets: ['latin'] })
 
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
  }) {
  
  const session = await getServerSession();
  return (
    <html lang="en" className='light'>
      <body>
        <SessionProvider session={session}>
          <NextUiClientProvider>
            <NavbarComponent/>
          {children}
          </NextUiClientProvider>
        </SessionProvider>
      </body>
    </html>
  )
}
